### ISSUE TITLE
Level two seems to be impossible

### ISSUE THREAD

**Issue by JannikHv** [Scarabol/rock-raiders-web#4]
I don't know if it's just me but I can't get through level 2 of the game. I seem to never have resource th build enough buildings and there aren't enough walls I can mine.

<img width="637" alt="Screenshot 2023-12-18 at 21 21 27" src="https://github.com/Scarabol/rock-raiders-web/assets/19554514/0be3cc11-b874-4509-8168-c34aa74db292">

**Comment by Scarabol** [comment]
Moin, the first 8 levels are tutorial levels, which have a lot of helper features. For example pointing arrows on game elements and in UI.

Unfortunately these are not implemented at the moment. I suggest you try one of the regular 25 levels, they should work as expected.

In doubt please refer to browser console for error messages and details.

**Comment by JannikHv** [comment]
Awesome, thanks for the info!
