### ISSUE TITLE
Bugged out monsters

### ISSUE THREAD

**Issue by JannikHv** [Scarabol/rock-raiders-web#6]
A smiliar behaviour as in https://github.com/Scarabol/rock-raiders-web/issues/5 occurs for monsters with the following error message:

<img width="734" alt="Screenshot 2024-01-10 at 11 25 26" src="https://github.com/Scarabol/rock-raiders-web/assets/19554514/706e0ff8-ffac-46a2-aa4b-d138d1c3a382">

Monsters just bug out and stand still for the rest of the mission sometimes. This problem curred on the master branch at this commit:
https://github.com/Scarabol/rock-raiders-web/commit/3f0c21f4f387949160b3baf90921be9e9d8f7baa

**Comment by JannikHv** [comment]
The problem here is that the bugged out monsters still fear the rock raiders and this makes it impossible to pass some ways.

The following changes inside the `RockMonsterBehaviorSystem.ts` file could solve the issue:

```ts
    private punchVehicle(behaviorComponent: RockMonsterBehaviorComponent, entity: number, sceneEntity: AnimatedSceneEntity, vehicleInMeleeRange: VehicleTarget, rockyPos: Vector2, stats: MonsterEntityStats) {
        const prevState = behaviorComponent.state
        this.ecs.removeComponent(entity, WorldTargetComponent)
        sceneEntity.lookAt(this.worldMgr.sceneMgr.getFloorPosition(vehicleInMeleeRange.position2d))
        behaviorComponent.state = RockMonsterBehaviorState.PUNCH
        sceneEntity.setAnimation(RockMonsterActivity.Punch, () => {
            sceneEntity.setAnimation(AnimEntityActivity.Stand)
            if (vehicleInMeleeRange.position2d.distanceToSquared(rockyPos) < ROCKY_MELEE_ATTACK_DISTANCE_SQ) {
                const vehicleComponents = this.ecs.getComponents(vehicleInMeleeRange.entity)

                if (vehicleComponents) {
                    const healthComponent = vehicleComponents.get(HealthComponent)

                    if (healthComponent) {
                        healthComponent.changeHealth(stats.RepairValue)

                        if (healthComponent.triggerAlarm) EventBus.publishEvent(new UnderAttackEvent(vehicleComponents.get(PositionComponent)))
                    }
                }
            }
            behaviorComponent.state = prevState
        })
    }
 ```

**Comment by Scarabol** [comment]
Thank you for this report and the screenshots. I could reproduce the issue and fix it in master branch.

There actually two issues involved here:
First: https://github.com/Scarabol/rock-raiders-web/commit/d04906c0bda6f8cdcfdbbda71b0850670fac0426#diff-d75993f89e2b0d25e1e2ad249a38c52e36d7bc307bfbb96396066cc960ab557eR382
Second: https://github.com/Scarabol/rock-raiders-web/commit/6b2853a55eb0e18206c8da592ab2fc4837a058ee#diff-d75993f89e2b0d25e1e2ad249a38c52e36d7bc307bfbb96396066cc960ab557eR382

**Comment by BlenderIsaac** [comment]
I have noticed rock monsters still bugging out and standing still, specifically in the level Hot Stuff
